// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Apo214__ActualizaFilaController from "./apo214/actualiza_fila_controller"
application.register("apo214--actualiza-fila", Apo214__ActualizaFilaController)

import Apo214__DragController from "./apo214/drag_controller"
application.register("apo214--drag", Apo214__DragController)

import Apo214__FormAsisreconocimientoController from "./apo214/form_asisreconocimiento_controller"
application.register("apo214--form-asisreconocimiento", Apo214__FormAsisreconocimientoController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import Sip__CancelarVacioEsEliminarController from "./sip/cancelar_vacio_es_eliminar_controller"
application.register("sip--cancelar-vacio-es-eliminar", Sip__CancelarVacioEsEliminarController)

import Sip__SindocautController from "./sip/sindocaut_controller"
application.register("sip--sindocaut", Sip__SindocautController)
