// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ActualizaFilaController from "./actualiza_fila_controller"
application.register("actualiza-fila", ActualizaFilaController)

import DragController from "./drag_controller"
application.register("drag", DragController)

import FormAsisreconocimientoController from "./form_asisreconocimiento_controller"
application.register("form-asisreconocimiento", FormAsisreconocimientoController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import Sip__CancelarVacioEsEliminarController from "./sip/cancelar_vacio_es_eliminar_controller"
application.register("sip--cancelar-vacio-es-eliminar", Sip__CancelarVacioEsEliminarController)
