// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Apo214__ActualizaFilaController from "./apo214/actualiza_fila_controller"
application.register("apo214--actualiza-fila", Apo214__ActualizaFilaController)

import Apo214__DragController from "./apo214/drag_controller"
application.register("apo214--drag", Apo214__DragController)

import Apo214__FormAsisreconocimientoController from "./apo214/form_asisreconocimiento_controller"
application.register("apo214--form-asisreconocimiento", Apo214__FormAsisreconocimientoController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import Msip__BitacoraapController from "./msip/bitacoraap_controller"
application.register("msip--bitacoraap", Msip__BitacoraapController)

import Msip__CancelarVacioEsEliminarController from "./msip/cancelar_vacio_es_eliminar_controller"
application.register("msip--cancelar-vacio-es-eliminar", Msip__CancelarVacioEsEliminarController)

import Msip__FiltroTanController from "./msip/filtro_tan_controller"
application.register("msip--filtro-tan", Msip__FiltroTanController)

import Msip__GeodepController from "./msip/geodep_controller"
application.register("msip--geodep", Msip__GeodepController)

import Msip__SindocautController from "./msip/sindocaut_controller"
application.register("msip--sindocaut", Msip__SindocautController)

import Sivel2Gen__ContarAutomaticoController from "./sivel2_gen/contar_automatico_controller"
application.register("sivel2-gen--contar-automatico", Sivel2Gen__ContarAutomaticoController)

import Sivel2Gen__EdadController from "./sivel2_gen/edad_controller"
application.register("sivel2-gen--edad", Sivel2Gen__EdadController)

import Sivel2Gen__EnviarFichaCasoController from "./sivel2_gen/enviar_ficha_caso_controller"
application.register("sivel2-gen--enviar-ficha-caso", Sivel2Gen__EnviarFichaCasoController)

import Sivel2Gen__FiltroAvanzadoController from "./sivel2_gen/filtro_avanzado_controller"
application.register("sivel2-gen--filtro-avanzado", Sivel2Gen__FiltroAvanzadoController)

import Sivel2Gen__MapaosmController from "./sivel2_gen/mapaosm_controller"
application.register("sivel2-gen--mapaosm", Sivel2Gen__MapaosmController)
